#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lor0138.Resource", IsApplication=true)]

namespace Lor0138
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Lorenzetti.Resource.Id.title = global::Lor0138.Resource.Id.title;
			global::Lorenzetti.Resource.String.app_name = global::Lor0138.Resource.String.app_name;
			global::Lorenzetti.Resource.String.hello = global::Lor0138.Resource.String.hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bordaazul = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bordapreta = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bordaverde = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_bg_rounded_corners = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int campofundobranco = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int down_arrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_aboutus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_client = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_contactus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_event = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_help = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_home = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_product = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_service = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_solution = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int loren_theme_button_disable = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int loren_theme_button_disable_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int loren_theme_button_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int loren_theme_button_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int loren_theme_button_selected = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int loren_theme_checkbox_off = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int loren_theme_checkbox_off_disabled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int loren_theme_checkbox_off_disabled_focused = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int loren_theme_checkbox_off_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int loren_theme_checkbox_off_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int loren_theme_checkbox_on = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int loren_theme_checkbox_on_disabled = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int loren_theme_checkbox_on_disabled_focused = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int loren_theme_checkbox_on_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int loren_theme_checkbox_on_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int loren_theme_dialog_body = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int loren_theme_dialog_body_fulldark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int loren_theme_dialog_footer = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int loren_theme_dialog_title = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int loren_theme_expander_close = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int loren_theme_expander_open = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int loren_theme_image_click_effect = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int loren_theme_listview_title = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int loren_theme_menu_more = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int loren_theme_progress_white = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int loren_theme_radio_off = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int loren_theme_radio_off_disabled = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int loren_theme_radio_off_disabled_focused = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int loren_theme_radio_off_focused = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int loren_theme_radio_off_pressed = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int loren_theme_radio_on = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int loren_theme_radio_on_disabled = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int loren_theme_radio_on_disabled_focused = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int loren_theme_radio_on_focused = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int loren_theme_radio_on_pressed = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int loren_theme_select_button = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int loren_theme_select_checkbox = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int loren_theme_select_edit_text = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int loren_theme_select_expander_group = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int loren_theme_select_radio = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int loren_theme_select_spinner_background = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int loren_theme_select_tab = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int loren_theme_select_textappearance_dropdownitem = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int loren_theme_shape_edit_text_actived = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int loren_theme_shape_edit_text_defaul = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int loren_theme_shape_edit_text_disabled = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int loren_theme_shape_edit_text_disabled_focused = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int loren_theme_shape_edit_text_focused = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int loren_theme_spinner_active = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int loren_theme_spinner_default = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int loren_theme_spinner_disabled = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int loren_theme_spinner_focused = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int loren_theme_spinner_pressed = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int loren_theme_spinner_white_48 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int loren_theme_tab_focus = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int loren_theme_tab_layout = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int loren_theme_tab_press = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int loren_theme_tab_selected = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int loren_theme_tab_unselected = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int menu_icon = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int up_arrow = 2130837580;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060120
			public const int ConsultaEstoque = 2131099936;
			
			// aapt resource value: 0x7f060148
			public const int ConsultaEstoqueBotoes = 2131099976;
			
			// aapt resource value: 0x7f060121
			public const int ConsultaEstoqueDados = 2131099937;
			
			// aapt resource value: 0x7f060122
			public const int ConsultaEstoqueLinha1 = 2131099938;
			
			// aapt resource value: 0x7f06013c
			public const int ConsultaEstoqueLinha10 = 2131099964;
			
			// aapt resource value: 0x7f06013e
			public const int ConsultaEstoqueLinha11 = 2131099966;
			
			// aapt resource value: 0x7f060139
			public const int ConsultaEstoqueLinha1111 = 2131099961;
			
			// aapt resource value: 0x7f060140
			public const int ConsultaEstoqueLinha12 = 2131099968;
			
			// aapt resource value: 0x7f060142
			public const int ConsultaEstoqueLinha13 = 2131099970;
			
			// aapt resource value: 0x7f060144
			public const int ConsultaEstoqueLinha14 = 2131099972;
			
			// aapt resource value: 0x7f060146
			public const int ConsultaEstoqueLinha15 = 2131099974;
			
			// aapt resource value: 0x7f060126
			public const int ConsultaEstoqueLinha2 = 2131099942;
			
			// aapt resource value: 0x7f060129
			public const int ConsultaEstoqueLinha3 = 2131099945;
			
			// aapt resource value: 0x7f06012c
			public const int ConsultaEstoqueLinha4 = 2131099948;
			
			// aapt resource value: 0x7f06012f
			public const int ConsultaEstoqueLinha5 = 2131099951;
			
			// aapt resource value: 0x7f060132
			public const int ConsultaEstoqueLinha6 = 2131099954;
			
			// aapt resource value: 0x7f060135
			public const int ConsultaEstoqueLinha7 = 2131099957;
			
			// aapt resource value: 0x7f060138
			public const int ConsultaEstoqueLinha8 = 2131099960;
			
			// aapt resource value: 0x7f06013b
			public const int ConsultaEstoqueLinha9 = 2131099963;
			
			// aapt resource value: 0x7f060000
			public const int ConsultaEstoqueSaldoLocal = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int ItemLinhaItem = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int btnImgExpander = 2131099657;
			
			// aapt resource value: 0x7f060158
			public const int btnLimpar = 2131099992;
			
			// aapt resource value: 0x7f060157
			public const int btnPesquisar = 2131099991;
			
			// aapt resource value: 0x7f06002c
			public const int cbxConsulta00Estoque = 2131099692;
			
			// aapt resource value: 0x7f060035
			public const int cbxConsulta00IesForcaApontamento = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int cbxConsulta00IesSofreBaixa = 2131099702;
			
			// aapt resource value: 0x7f060032
			public const int cbxConsulta00Inspecao = 2131099698;
			
			// aapt resource value: 0x7f06010e
			public const int cbxConsultaFiscalContabiliza = 2131099918;
			
			// aapt resource value: 0x7f06010f
			public const int cbxConsultaFiscalCreditoPisCofins = 2131099919;
			
			// aapt resource value: 0x7f060088
			public const int cbxConsultaManufaturaControlaEstoque = 2131099784;
			
			// aapt resource value: 0x7f06008d
			public const int cbxConsultaManufaturaControlaInspecao = 2131099789;
			
			// aapt resource value: 0x7f0600a8
			public const int cbxConsultaManufaturaControlaLote = 2131099816;
			
			// aapt resource value: 0x7f0600a4
			public const int cbxConsultaManufaturaIqpf = 2131099812;
			
			// aapt resource value: 0x7f0600ac
			public const int cbxConsultaManufaturaProduzidoEmpresa = 2131099820;
			
			// aapt resource value: 0x7f0600ee
			public const int cbxConsultaPlanejamentoApontamento = 2131099886;
			
			// aapt resource value: 0x7f0600ef
			public const int cbxConsultaPlanejamentoApontamentoAutomatico = 2131099887;
			
			// aapt resource value: 0x7f0600f8
			public const int cbxConsultaPlanejamentoControleFisico = 2131099896;
			
			// aapt resource value: 0x7f0600e0
			public const int cbxConsultaPlanejamentoForcaApontamento = 2131099872;
			
			// aapt resource value: 0x7f0600ea
			public const int cbxConsultaPlanejamentoImpedidoAposInspecao = 2131099882;
			
			// aapt resource value: 0x7f0600f4
			public const int cbxConsultaPlanejamentoInterfereQualidadeProdutoFinal = 2131099892;
			
			// aapt resource value: 0x7f0600ec
			public const int cbxConsultaPlanejamentoListaOrdens = 2131099884;
			
			// aapt resource value: 0x7f0600ed
			public const int cbxConsultaPlanejamentoListaRoteiro = 2131099885;
			
			// aapt resource value: 0x7f0600f9
			public const int cbxConsultaPlanejamentoProduzidoNaEmpresa = 2131099897;
			
			// aapt resource value: 0x7f06000f
			public const int consulta00 = 2131099663;
			
			// aapt resource value: 0x7f060055
			public const int consulta00botoes = 2131099733;
			
			// aapt resource value: 0x7f060010
			public const int consulta00dados = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int consulta00linha1 = 2131099665;
			
			// aapt resource value: 0x7f060047
			public const int consulta00linha10 = 2131099719;
			
			// aapt resource value: 0x7f06004a
			public const int consulta00linha11 = 2131099722;
			
			// aapt resource value: 0x7f06004d
			public const int consulta00linha12 = 2131099725;
			
			// aapt resource value: 0x7f060050
			public const int consulta00linha13 = 2131099728;
			
			// aapt resource value: 0x7f060053
			public const int consulta00linha14 = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int consulta00linha15 = 2131099732;
			
			// aapt resource value: 0x7f060016
			public const int consulta00linha2 = 2131099670;
			
			// aapt resource value: 0x7f06001d
			public const int consulta00linha3 = 2131099677;
			
			// aapt resource value: 0x7f060024
			public const int consulta00linha4 = 2131099684;
			
			// aapt resource value: 0x7f06002b
			public const int consulta00linha5 = 2131099691;
			
			// aapt resource value: 0x7f060031
			public const int consulta00linha6 = 2131099697;
			
			// aapt resource value: 0x7f060039
			public const int consulta00linha7 = 2131099705;
			
			// aapt resource value: 0x7f06003f
			public const int consulta00linha8 = 2131099711;
			
			// aapt resource value: 0x7f060044
			public const int consulta00linha9 = 2131099716;
			
			// aapt resource value: 0x7f060056
			public const int consultaDimensionais = 2131099734;
			
			// aapt resource value: 0x7f060058
			public const int consultaDimensionaisLinha1 = 2131099736;
			
			// aapt resource value: 0x7f060070
			public const int consultaDimensionaisLinha10 = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int consultaDimensionaisLinha11 = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int consultaDimensionaisLinha12 = 2131099762;
			
			// aapt resource value: 0x7f060075
			public const int consultaDimensionaisLinha13 = 2131099765;
			
			// aapt resource value: 0x7f060077
			public const int consultaDimensionaisLinha14 = 2131099767;
			
			// aapt resource value: 0x7f06007a
			public const int consultaDimensionaisLinha15 = 2131099770;
			
			// aapt resource value: 0x7f060059
			public const int consultaDimensionaisLinha2 = 2131099737;
			
			// aapt resource value: 0x7f06005c
			public const int consultaDimensionaisLinha3 = 2131099740;
			
			// aapt resource value: 0x7f060060
			public const int consultaDimensionaisLinha4 = 2131099744;
			
			// aapt resource value: 0x7f060064
			public const int consultaDimensionaisLinha5 = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int consultaDimensionaisLinha6 = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int consultaDimensionaisLinha7 = 2131099750;
			
			// aapt resource value: 0x7f060068
			public const int consultaDimensionaisLinha8 = 2131099752;
			
			// aapt resource value: 0x7f06006c
			public const int consultaDimensionaisLinha9 = 2131099756;
			
			// aapt resource value: 0x7f06007b
			public const int consultaDimensionaisbotoes = 2131099771;
			
			// aapt resource value: 0x7f060057
			public const int consultaDimensionaisdados = 2131099735;
			
			// aapt resource value: 0x7f0600fd
			public const int consultaFiscal = 2131099901;
			
			// aapt resource value: 0x7f06011f
			public const int consultaFiscalBotoes = 2131099935;
			
			// aapt resource value: 0x7f0600fe
			public const int consultaFiscalDados = 2131099902;
			
			// aapt resource value: 0x7f0600ff
			public const int consultaFiscalLinha1 = 2131099903;
			
			// aapt resource value: 0x7f060119
			public const int consultaFiscalLinha10 = 2131099929;
			
			// aapt resource value: 0x7f06011a
			public const int consultaFiscalLinha11 = 2131099930;
			
			// aapt resource value: 0x7f06011b
			public const int consultaFiscalLinha12 = 2131099931;
			
			// aapt resource value: 0x7f06011c
			public const int consultaFiscalLinha13 = 2131099932;
			
			// aapt resource value: 0x7f06011d
			public const int consultaFiscalLinha14 = 2131099933;
			
			// aapt resource value: 0x7f06011e
			public const int consultaFiscalLinha15 = 2131099934;
			
			// aapt resource value: 0x7f060103
			public const int consultaFiscalLinha2 = 2131099907;
			
			// aapt resource value: 0x7f060107
			public const int consultaFiscalLinha3 = 2131099911;
			
			// aapt resource value: 0x7f06010c
			public const int consultaFiscalLinha4 = 2131099916;
			
			// aapt resource value: 0x7f060110
			public const int consultaFiscalLinha5 = 2131099920;
			
			// aapt resource value: 0x7f060115
			public const int consultaFiscalLinha6 = 2131099925;
			
			// aapt resource value: 0x7f060116
			public const int consultaFiscalLinha7 = 2131099926;
			
			// aapt resource value: 0x7f060117
			public const int consultaFiscalLinha8 = 2131099927;
			
			// aapt resource value: 0x7f060118
			public const int consultaFiscalLinha9 = 2131099928;
			
			// aapt resource value: 0x7f06007c
			public const int consultaManufatura = 2131099772;
			
			// aapt resource value: 0x7f0600bd
			public const int consultaManufaturaBotoes = 2131099837;
			
			// aapt resource value: 0x7f06007d
			public const int consultaManufaturaDados = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int consultaManufaturaLinha1 = 2131099774;
			
			// aapt resource value: 0x7f0600a9
			public const int consultaManufaturaLinha10 = 2131099817;
			
			// aapt resource value: 0x7f0600ad
			public const int consultaManufaturaLinha11 = 2131099821;
			
			// aapt resource value: 0x7f0600af
			public const int consultaManufaturaLinha12 = 2131099823;
			
			// aapt resource value: 0x7f0600b1
			public const int consultaManufaturaLinha14 = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int consultaManufaturaLinha15 = 2131099826;
			
			// aapt resource value: 0x7f060082
			public const int consultaManufaturaLinha2 = 2131099778;
			
			// aapt resource value: 0x7f060087
			public const int consultaManufaturaLinha3 = 2131099783;
			
			// aapt resource value: 0x7f06008c
			public const int consultaManufaturaLinha4 = 2131099788;
			
			// aapt resource value: 0x7f060092
			public const int consultaManufaturaLinha5 = 2131099794;
			
			// aapt resource value: 0x7f060097
			public const int consultaManufaturaLinha6 = 2131099799;
			
			// aapt resource value: 0x7f06009c
			public const int consultaManufaturaLinha7 = 2131099804;
			
			// aapt resource value: 0x7f0600a1
			public const int consultaManufaturaLinha8 = 2131099809;
			
			// aapt resource value: 0x7f0600a5
			public const int consultaManufaturaLinha9 = 2131099813;
			
			// aapt resource value: 0x7f0600be
			public const int consultaPlanejamento = 2131099838;
			
			// aapt resource value: 0x7f0600fc
			public const int consultaPlanejamentoBotoes = 2131099900;
			
			// aapt resource value: 0x7f0600bf
			public const int consultaPlanejamentoDados = 2131099839;
			
			// aapt resource value: 0x7f0600c0
			public const int consultaPlanejamentoLinha1 = 2131099840;
			
			// aapt resource value: 0x7f0600e8
			public const int consultaPlanejamentoLinha10 = 2131099880;
			
			// aapt resource value: 0x7f0600eb
			public const int consultaPlanejamentoLinha11 = 2131099883;
			
			// aapt resource value: 0x7f0600f1
			public const int consultaPlanejamentoLinha12 = 2131099889;
			
			// aapt resource value: 0x7f0600f5
			public const int consultaPlanejamentoLinha13 = 2131099893;
			
			// aapt resource value: 0x7f0600fa
			public const int consultaPlanejamentoLinha14 = 2131099898;
			
			// aapt resource value: 0x7f0600fb
			public const int consultaPlanejamentoLinha15 = 2131099899;
			
			// aapt resource value: 0x7f0600c4
			public const int consultaPlanejamentoLinha2 = 2131099844;
			
			// aapt resource value: 0x7f0600c8
			public const int consultaPlanejamentoLinha3 = 2131099848;
			
			// aapt resource value: 0x7f0600cc
			public const int consultaPlanejamentoLinha4 = 2131099852;
			
			// aapt resource value: 0x7f0600d1
			public const int consultaPlanejamentoLinha5 = 2131099857;
			
			// aapt resource value: 0x7f0600d8
			public const int consultaPlanejamentoLinha6 = 2131099864;
			
			// aapt resource value: 0x7f0600dd
			public const int consultaPlanejamentoLinha7 = 2131099869;
			
			// aapt resource value: 0x7f0600e2
			public const int consultaPlanejamentoLinha8 = 2131099874;
			
			// aapt resource value: 0x7f0600e5
			public const int consultaPlanejamentoLinha9 = 2131099877;
			
			// aapt resource value: 0x7f060149
			public const int filtro = 2131099977;
			
			// aapt resource value: 0x7f060008
			public const int imgProfilePic = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int item = 2131099658;
			
			// aapt resource value: 0x7f06015a
			public const int ivMenuImg = 2131099994;
			
			// aapt resource value: 0x7f06014a
			public const int linhaCodigoItem = 2131099978;
			
			// aapt resource value: 0x7f06014c
			public const int linhaDescricaoItem = 2131099980;
			
			// aapt resource value: 0x7f060152
			public const int linhaLinhaProduto = 2131099986;
			
			// aapt resource value: 0x7f06014e
			public const int linhaTipoItem = 2131099982;
			
			// aapt resource value: 0x7f06015c
			public const int llPopUp = 2131099996;
			
			// aapt resource value: 0x7f06013a
			public const int lvwConsultaEstoqueSaldoLocal = 2131099962;
			
			// aapt resource value: 0x7f06015d
			public const int lvwDetalhe = 2131099997;
			
			// aapt resource value: 0x7f060006
			public const int menuIconImgView = 2131099654;
			
			// aapt resource value: 0x7f060159
			public const int menuListView = 2131099993;
			
			// aapt resource value: 0x7f060124
			public const int textView = 2131099940;
			
			// aapt resource value: 0x7f060160
			public const int title = 2131100000;
			
			// aapt resource value: 0x7f060005
			public const int titleBarLinearLayout = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int txtActionBarText = 2131099655;
			
			// aapt resource value: 0x7f06015e
			public const int txtCodigoItem = 2131099998;
			
			// aapt resource value: 0x7f060015
			public const int txtConsulta00AliquotaIpi = 2131099669;
			
			// aapt resource value: 0x7f060051
			public const int txtConsulta00CodigoClasseUso = 2131099729;
			
			// aapt resource value: 0x7f060012
			public const int txtConsulta00CodigoClassificacaoFiscal = 2131099666;
			
			// aapt resource value: 0x7f060042
			public const int txtConsulta00CodigoComprador = 2131099714;
			
			// aapt resource value: 0x7f060017
			public const int txtConsulta00CodigoContenedor = 2131099671;
			
			// aapt resource value: 0x7f060020
			public const int txtConsulta00CodigoFamilia = 2131099680;
			
			// aapt resource value: 0x7f060025
			public const int txtConsulta00CodigoGrupoControleEstoque = 2131099685;
			
			// aapt resource value: 0x7f060013
			public const int txtConsulta00CodigoIncidenciaIcms = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int txtConsulta00CodigoIncidenciaIpi = 2131099668;
			
			// aapt resource value: 0x7f060048
			public const int txtConsulta00CodigoLinhaProduto = 2131099720;
			
			// aapt resource value: 0x7f06004b
			public const int txtConsulta00CodigoLinhaReceita = 2131099723;
			
			// aapt resource value: 0x7f06002d
			public const int txtConsulta00CodigoLocalEstoque = 2131099693;
			
			// aapt resource value: 0x7f060033
			public const int txtConsulta00CodigoLocalInspecao = 2131099699;
			
			// aapt resource value: 0x7f06002f
			public const int txtConsulta00CodigoLocalProducao = 2131099695;
			
			// aapt resource value: 0x7f06001b
			public const int txtConsulta00CodigoPainel = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int txtConsulta00CodigoPainelFisico = 2131099676;
			
			// aapt resource value: 0x7f06003d
			public const int txtConsulta00CodigoProgramador = 2131099709;
			
			// aapt resource value: 0x7f06004e
			public const int txtConsulta00CodigoSegmentoMercado = 2131099726;
			
			// aapt resource value: 0x7f060027
			public const int txtConsulta00CodigoSituacao0022 = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int txtConsulta00CodigoSituacao0770 = 2131099689;
			
			// aapt resource value: 0x7f06001e
			public const int txtConsulta00CodigoTipoItem = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int txtConsulta00DataCadastro = 2131099682;
			
			// aapt resource value: 0x7f060052
			public const int txtConsulta00DescricaoClasseUso = 2131099730;
			
			// aapt resource value: 0x7f060018
			public const int txtConsulta00DescricaoContenedor = 2131099672;
			
			// aapt resource value: 0x7f060021
			public const int txtConsulta00DescricaoFamilia = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int txtConsulta00DescricaoGrupoControleEstoque = 2131099686;
			
			// aapt resource value: 0x7f060049
			public const int txtConsulta00DescricaoLinhaProduto = 2131099721;
			
			// aapt resource value: 0x7f06004c
			public const int txtConsulta00DescricaoLinhaReceita = 2131099724;
			
			// aapt resource value: 0x7f06002e
			public const int txtConsulta00DescricaoLocalEstoque = 2131099694;
			
			// aapt resource value: 0x7f060034
			public const int txtConsulta00DescricaoLocalInspecao = 2131099700;
			
			// aapt resource value: 0x7f060030
			public const int txtConsulta00DescricaoLocalProducao = 2131099696;
			
			// aapt resource value: 0x7f06004f
			public const int txtConsulta00DescricaoSegmentoMercado = 2131099727;
			
			// aapt resource value: 0x7f060028
			public const int txtConsulta00DescricaoSituacao0022 = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int txtConsulta00DescricaoSituacao0770 = 2131099690;
			
			// aapt resource value: 0x7f06001f
			public const int txtConsulta00DescricaoTipoItem = 2131099679;
			
			// aapt resource value: 0x7f060037
			public const int txtConsulta00IesAberturaLiberacao = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int txtConsulta00IesPlanejamento = 2131099704;
			
			// aapt resource value: 0x7f060043
			public const int txtConsulta00NomeComprador = 2131099715;
			
			// aapt resource value: 0x7f06003e
			public const int txtConsulta00NomeProgramador = 2131099710;
			
			// aapt resource value: 0x7f060023
			public const int txtConsulta00ProdutoChave = 2131099683;
			
			// aapt resource value: 0x7f06003b
			public const int txtConsulta00QuantidadeDiasEstoqueSeguranca = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int txtConsulta00QuantidadeDiasRessuprimento = 2131099708;
			
			// aapt resource value: 0x7f06001a
			public const int txtConsulta00QuantidadeEmpilhamentoMaximo = 2131099674;
			
			// aapt resource value: 0x7f06003a
			public const int txtConsulta00QuantidadeEstoqueSeguranca = 2131099706;
			
			// aapt resource value: 0x7f060019
			public const int txtConsulta00QuantidadeItensContenedor = 2131099673;
			
			// aapt resource value: 0x7f060046
			public const int txtConsulta00QuantidadeProgramacaoFixa = 2131099718;
			
			// aapt resource value: 0x7f060041
			public const int txtConsulta00QuantidadeProgramacaoMaxima = 2131099713;
			
			// aapt resource value: 0x7f060040
			public const int txtConsulta00QuantidadeProgramacaoMinima = 2131099712;
			
			// aapt resource value: 0x7f060045
			public const int txtConsulta00QuantidadeProgramacaoMultipla = 2131099717;
			
			// aapt resource value: 0x7f06006b
			public const int txtConsultaDimensionaisEmbalagemAltura = 2131099755;
			
			// aapt resource value: 0x7f060069
			public const int txtConsultaDimensionaisEmbalagemComprimento = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int txtConsultaDimensionaisEmbalagemLargura = 2131099754;
			
			// aapt resource value: 0x7f06006e
			public const int txtConsultaDimensionaisEmbalagemPesoCheia = 2131099758;
			
			// aapt resource value: 0x7f06006d
			public const int txtConsultaDimensionaisEmbalagemPesoVazia = 2131099757;
			
			// aapt resource value: 0x7f06006f
			public const int txtConsultaDimensionaisEmbalagemVolume = 2131099759;
			
			// aapt resource value: 0x7f060079
			public const int txtConsultaDimensionaisPaletePeso = 2131099769;
			
			// aapt resource value: 0x7f060073
			public const int txtConsultaDimensionaisPaleteQuantidadeCaixasCamada = 2131099763;
			
			// aapt resource value: 0x7f060076
			public const int txtConsultaDimensionaisPaleteQuantidadeCaixasColetivas = 2131099766;
			
			// aapt resource value: 0x7f060074
			public const int txtConsultaDimensionaisPaleteQuantidadeCamadas = 2131099764;
			
			// aapt resource value: 0x7f060078
			public const int txtConsultaDimensionaisPaleteQuantidadeEmbalagensVendaVarejo = 2131099768;
			
			// aapt resource value: 0x7f06005f
			public const int txtConsultaDimensionaisProdutoAltura = 2131099743;
			
			// aapt resource value: 0x7f06005d
			public const int txtConsultaDimensionaisProdutoComprimento = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int txtConsultaDimensionaisProdutoLargura = 2131099742;
			
			// aapt resource value: 0x7f060061
			public const int txtConsultaDimensionaisProdutoPeso = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int txtConsultaDimensionaisProdutoVolume = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int txtConsultaDimensionaisProdutoVolumeAdicional = 2131099747;
			
			// aapt resource value: 0x7f06005b
			public const int txtConsultaDimensionaisQuantidadeItensCaixa = 2131099739;
			
			// aapt resource value: 0x7f06005a
			public const int txtConsultaDimensionaisQuantidadePecasItem = 2131099738;
			
			// aapt resource value: 0x7f060137
			public const int txtConsultaEstoqueDataUltimaSaida = 2131099959;
			
			// aapt resource value: 0x7f060147
			public const int txtConsultaEstoqueMediaConsumo01Mes = 2131099975;
			
			// aapt resource value: 0x7f060145
			public const int txtConsultaEstoqueMediaConsumo02Meses = 2131099973;
			
			// aapt resource value: 0x7f060143
			public const int txtConsultaEstoqueMediaConsumo03Meses = 2131099971;
			
			// aapt resource value: 0x7f060141
			public const int txtConsultaEstoqueMediaConsumo06Meses = 2131099969;
			
			// aapt resource value: 0x7f06013f
			public const int txtConsultaEstoqueMediaConsumo09Meses = 2131099967;
			
			// aapt resource value: 0x7f06013d
			public const int txtConsultaEstoqueMediaConsumo12Meses = 2131099965;
			
			// aapt resource value: 0x7f060133
			public const int txtConsultaEstoqueQuantidadeConsignada = 2131099955;
			
			// aapt resource value: 0x7f06012b
			public const int txtConsultaEstoqueQuantidadeDeTerceiros = 2131099947;
			
			// aapt resource value: 0x7f060128
			public const int txtConsultaEstoqueQuantidadeEmInspecao = 2131099944;
			
			// aapt resource value: 0x7f06012d
			public const int txtConsultaEstoqueQuantidadeEmProcessoContagem = 2131099949;
			
			// aapt resource value: 0x7f06012a
			public const int txtConsultaEstoqueQuantidadeEmTerceiros = 2131099946;
			
			// aapt resource value: 0x7f06012e
			public const int txtConsultaEstoqueQuantidadeEmTransito = 2131099950;
			
			// aapt resource value: 0x7f060131
			public const int txtConsultaEstoqueQuantidadeEntregaFutura = 2131099953;
			
			// aapt resource value: 0x7f060125
			public const int txtConsultaEstoqueQuantidadeLiberadaExcepcionalmente = 2131099941;
			
			// aapt resource value: 0x7f060123
			public const int txtConsultaEstoqueQuantidadeLiberadaNormal = 2131099939;
			
			// aapt resource value: 0x7f060134
			public const int txtConsultaEstoqueQuantidadeLiberadoExcepcionalmente = 2131099956;
			
			// aapt resource value: 0x7f060136
			public const int txtConsultaEstoqueQuantidadeLiberadoNormal = 2131099958;
			
			// aapt resource value: 0x7f060130
			public const int txtConsultaEstoqueQuantidadeNaEmpresa = 2131099952;
			
			// aapt resource value: 0x7f060127
			public const int txtConsultaEstoqueQuantidadeRejeitada = 2131099943;
			
			// aapt resource value: 0x7f060001
			public const int txtConsultaEstoqueSaldoLocalCodigoLocal = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int txtConsultaEstoqueSaldoLocalNumeroLote = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int txtConsultaEstoqueSaldoLocalQuantidade = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int txtConsultaEstoqueSaldoLocalSituacao = 2131099651;
			
			// aapt resource value: 0x7f060109
			public const int txtConsultaFiscalAliquotaIpi = 2131099913;
			
			// aapt resource value: 0x7f060108
			public const int txtConsultaFiscalClassificacaoFiscal = 2131099912;
			
			// aapt resource value: 0x7f06010d
			public const int txtConsultaFiscalCodigoFiscal = 2131099917;
			
			// aapt resource value: 0x7f060100
			public const int txtConsultaFiscalCodigoGrupoDespesa = 2131099904;
			
			// aapt resource value: 0x7f060111
			public const int txtConsultaFiscalCodigoOrigem = 2131099921;
			
			// aapt resource value: 0x7f060104
			public const int txtConsultaFiscalCodigoTipoDespesa = 2131099908;
			
			// aapt resource value: 0x7f060113
			public const int txtConsultaFiscalCodigoTipoItemSped = 2131099923;
			
			// aapt resource value: 0x7f060102
			public const int txtConsultaFiscalContaContabil = 2131099906;
			
			// aapt resource value: 0x7f060101
			public const int txtConsultaFiscalDescricaoGrupoDespesa = 2131099905;
			
			// aapt resource value: 0x7f06010b
			public const int txtConsultaFiscalDescricaoIncidenciaIcms = 2131099915;
			
			// aapt resource value: 0x7f06010a
			public const int txtConsultaFiscalDescricaoIncidenciaIpi = 2131099914;
			
			// aapt resource value: 0x7f060112
			public const int txtConsultaFiscalDescricaoOrigem = 2131099922;
			
			// aapt resource value: 0x7f060105
			public const int txtConsultaFiscalDescricaoTipoDespesa = 2131099909;
			
			// aapt resource value: 0x7f060114
			public const int txtConsultaFiscalDescricaoTipoItemSped = 2131099924;
			
			// aapt resource value: 0x7f060106
			public const int txtConsultaFiscalNomeContaContabil = 2131099910;
			
			// aapt resource value: 0x7f0600b5
			public const int txtConsultaManufaturaAltura = 2131099829;
			
			// aapt resource value: 0x7f0600b9
			public const int txtConsultaManufaturaCaixasEmbalagem = 2131099833;
			
			// aapt resource value: 0x7f0600bb
			public const int txtConsultaManufaturaCamadasPalete = 2131099835;
			
			// aapt resource value: 0x7f0600aa
			public const int txtConsultaManufaturaCodigoClasseUso = 2131099818;
			
			// aapt resource value: 0x7f06009f
			public const int txtConsultaManufaturaCodigoComponenteCusto = 2131099807;
			
			// aapt resource value: 0x7f060093
			public const int txtConsultaManufaturaCodigoFamilia = 2131099795;
			
			// aapt resource value: 0x7f060098
			public const int txtConsultaManufaturaCodigoGrupoControleEstoque = 2131099800;
			
			// aapt resource value: 0x7f06009d
			public const int txtConsultaManufaturaCodigoLinhaProduto = 2131099805;
			
			// aapt resource value: 0x7f0600a2
			public const int txtConsultaManufaturaCodigoLinhaReceita = 2131099810;
			
			// aapt resource value: 0x7f060089
			public const int txtConsultaManufaturaCodigoLocalEstoque = 2131099785;
			
			// aapt resource value: 0x7f06008e
			public const int txtConsultaManufaturaCodigoLocalInspecao = 2131099790;
			
			// aapt resource value: 0x7f0600a6
			public const int txtConsultaManufaturaCodigoSegmentoMercado = 2131099814;
			
			// aapt resource value: 0x7f060095
			public const int txtConsultaManufaturaCodigoSituacao0022 = 2131099797;
			
			// aapt resource value: 0x7f06009a
			public const int txtConsultaManufaturaCodigoSituacao0770 = 2131099802;
			
			// aapt resource value: 0x7f060090
			public const int txtConsultaManufaturaCodigoTipoItem = 2131099792;
			
			// aapt resource value: 0x7f06007f
			public const int txtConsultaManufaturaCodigoUnidadeMedida = 2131099775;
			
			// aapt resource value: 0x7f0600b3
			public const int txtConsultaManufaturaComprimento = 2131099827;
			
			// aapt resource value: 0x7f060086
			public const int txtConsultaManufaturaDataCadastro = 2131099782;
			
			// aapt resource value: 0x7f0600ab
			public const int txtConsultaManufaturaDescricaoClasseUso = 2131099819;
			
			// aapt resource value: 0x7f0600a0
			public const int txtConsultaManufaturaDescricaoComponenteCusto = 2131099808;
			
			// aapt resource value: 0x7f0600ae
			public const int txtConsultaManufaturaDescricaoEan13 = 2131099822;
			
			// aapt resource value: 0x7f060094
			public const int txtConsultaManufaturaDescricaoFamilia = 2131099796;
			
			// aapt resource value: 0x7f060099
			public const int txtConsultaManufaturaDescricaoGrupoControleEstoque = 2131099801;
			
			// aapt resource value: 0x7f06009e
			public const int txtConsultaManufaturaDescricaoLinhaProduto = 2131099806;
			
			// aapt resource value: 0x7f0600a3
			public const int txtConsultaManufaturaDescricaoLinhaReceita = 2131099811;
			
			// aapt resource value: 0x7f06008a
			public const int txtConsultaManufaturaDescricaoLocalEstoque = 2131099786;
			
			// aapt resource value: 0x7f06008f
			public const int txtConsultaManufaturaDescricaoLocalInspecao = 2131099791;
			
			// aapt resource value: 0x7f0600a7
			public const int txtConsultaManufaturaDescricaoSegmentoMercado = 2131099815;
			
			// aapt resource value: 0x7f060096
			public const int txtConsultaManufaturaDescricaoSituacao0022 = 2131099798;
			
			// aapt resource value: 0x7f06009b
			public const int txtConsultaManufaturaDescricaoSituacao0770 = 2131099803;
			
			// aapt resource value: 0x7f060091
			public const int txtConsultaManufaturaDescricaoTipoItem = 2131099793;
			
			// aapt resource value: 0x7f060080
			public const int txtConsultaManufaturaDescricaoUnidadeMedida = 2131099776;
			
			// aapt resource value: 0x7f0600ba
			public const int txtConsultaManufaturaEmbalagensCamada = 2131099834;
			
			// aapt resource value: 0x7f0600bc
			public const int txtConsultaManufaturaEmbalagensPalete = 2131099836;
			
			// aapt resource value: 0x7f0600b0
			public const int txtConsultaManufaturaEspecificacoes = 2131099824;
			
			// aapt resource value: 0x7f060081
			public const int txtConsultaManufaturaFatorConversao = 2131099777;
			
			// aapt resource value: 0x7f0600b8
			public const int txtConsultaManufaturaItensCaixa = 2131099832;
			
			// aapt resource value: 0x7f0600b4
			public const int txtConsultaManufaturaLargura = 2131099828;
			
			// aapt resource value: 0x7f0600b7
			public const int txtConsultaManufaturaPecasItem = 2131099831;
			
			// aapt resource value: 0x7f060085
			public const int txtConsultaManufaturaPesoEmbalagem = 2131099781;
			
			// aapt resource value: 0x7f060084
			public const int txtConsultaManufaturaPesoEmbalagemVazia = 2131099780;
			
			// aapt resource value: 0x7f060083
			public const int txtConsultaManufaturaPesoUnitario = 2131099779;
			
			// aapt resource value: 0x7f06008b
			public const int txtConsultaManufaturaTipoApontamento = 2131099787;
			
			// aapt resource value: 0x7f0600b6
			public const int txtConsultaManufaturaVolume = 2131099830;
			
			// aapt resource value: 0x7f0600e7
			public const int txtConsultaPlanejamentoAberturaLiberacao = 2131099879;
			
			// aapt resource value: 0x7f0600e6
			public const int txtConsultaPlanejamentoApontamentoMrp = 2131099878;
			
			// aapt resource value: 0x7f0600e4
			public const int txtConsultaPlanejamentoBaixaComponentes = 2131099876;
			
			// aapt resource value: 0x7f0600f6
			public const int txtConsultaPlanejamentoCodigoComprador = 2131099894;
			
			// aapt resource value: 0x7f0600cf
			public const int txtConsultaPlanejamentoCodigoHorizonte = 2131099855;
			
			// aapt resource value: 0x7f0600c9
			public const int txtConsultaPlanejamentoCodigoLocalProducao = 2131099849;
			
			// aapt resource value: 0x7f0600f2
			public const int txtConsultaPlanejamentoCodigoProgramador = 2131099890;
			
			// aapt resource value: 0x7f0600c1
			public const int txtConsultaPlanejamentoCodigoRoteiro = 2131099841;
			
			// aapt resource value: 0x7f0600c3
			public const int txtConsultaPlanejamentoCodigoRoteiroAlternativo = 2131099843;
			
			// aapt resource value: 0x7f0600c6
			public const int txtConsultaPlanejamentoCodigoUnidadeMedida = 2131099846;
			
			// aapt resource value: 0x7f0600ca
			public const int txtConsultaPlanejamentoDescricaoLocalProducao = 2131099850;
			
			// aapt resource value: 0x7f0600c2
			public const int txtConsultaPlanejamentoDescricaoRoteiro = 2131099842;
			
			// aapt resource value: 0x7f0600c7
			public const int txtConsultaPlanejamentoDescricaoUnidadeMedida = 2131099847;
			
			// aapt resource value: 0x7f0600df
			public const int txtConsultaPlanejamentoEstoqueMaximo = 2131099871;
			
			// aapt resource value: 0x7f0600de
			public const int txtConsultaPlanejamentoEstoqueSeguranca = 2131099870;
			
			// aapt resource value: 0x7f0600c5
			public const int txtConsultaPlanejamentoFatorConversao = 2131099845;
			
			// aapt resource value: 0x7f0600d0
			public const int txtConsultaPlanejamentoNivel = 2131099856;
			
			// aapt resource value: 0x7f0600f7
			public const int txtConsultaPlanejamentoNomeComprador = 2131099895;
			
			// aapt resource value: 0x7f0600f3
			public const int txtConsultaPlanejamentoNomeProgramador = 2131099891;
			
			// aapt resource value: 0x7f0600cb
			public const int txtConsultaPlanejamentoPercentualRefugo = 2131099851;
			
			// aapt resource value: 0x7f0600e3
			public const int txtConsultaPlanejamentoPlanejamento = 2131099875;
			
			// aapt resource value: 0x7f0600dc
			public const int txtConsultaPlanejamentoProgramacaoFixa = 2131099868;
			
			// aapt resource value: 0x7f0600da
			public const int txtConsultaPlanejamentoProgramacaoMaxima = 2131099866;
			
			// aapt resource value: 0x7f0600d9
			public const int txtConsultaPlanejamentoProgramacaoMinima = 2131099865;
			
			// aapt resource value: 0x7f0600db
			public const int txtConsultaPlanejamentoProgramacaoMultipla = 2131099867;
			
			// aapt resource value: 0x7f0600f0
			public const int txtConsultaPlanejamentoQuantidadeDecimais = 2131099888;
			
			// aapt resource value: 0x7f0600ce
			public const int txtConsultaPlanejamentoQuantidadeDiasEstoqueSeguranca = 2131099854;
			
			// aapt resource value: 0x7f0600cd
			public const int txtConsultaPlanejamentoQuantidadeEstoqueSeguranca = 2131099853;
			
			// aapt resource value: 0x7f0600e1
			public const int txtConsultaPlanejamentoSofreBaixa = 2131099873;
			
			// aapt resource value: 0x7f0600d7
			public const int txtConsultaPlanejamentoTempoContagem = 2131099863;
			
			// aapt resource value: 0x7f0600d4
			public const int txtConsultaPlanejamentoTempoFabricacao = 2131099860;
			
			// aapt resource value: 0x7f0600d6
			public const int txtConsultaPlanejamentoTempoInspecao = 2131099862;
			
			// aapt resource value: 0x7f0600d3
			public const int txtConsultaPlanejamentoTempoPedido = 2131099859;
			
			// aapt resource value: 0x7f0600d2
			public const int txtConsultaPlanejamentoTempoRessuprimento = 2131099858;
			
			// aapt resource value: 0x7f0600d5
			public const int txtConsultaPlanejamentoTempoTransporte = 2131099861;
			
			// aapt resource value: 0x7f0600e9
			public const int txtConsultaPlanejamentoTipoApontamento = 2131099881;
			
			// aapt resource value: 0x7f06015f
			public const int txtDescricaoItem = 2131099999;
			
			// aapt resource value: 0x7f060156
			public const int txtFiltroCodigoClasseUso = 2131099990;
			
			// aapt resource value: 0x7f060150
			public const int txtFiltroCodigoFamilia = 2131099984;
			
			// aapt resource value: 0x7f060151
			public const int txtFiltroCodigoGrupoControleEstoque = 2131099985;
			
			// aapt resource value: 0x7f06014b
			public const int txtFiltroCodigoItem = 2131099979;
			
			// aapt resource value: 0x7f060153
			public const int txtFiltroCodigoLinhaProduto = 2131099987;
			
			// aapt resource value: 0x7f060154
			public const int txtFiltroCodigoLinhaReceita = 2131099988;
			
			// aapt resource value: 0x7f060155
			public const int txtFiltroCodigoSegmentoMercado = 2131099989;
			
			// aapt resource value: 0x7f06014f
			public const int txtFiltroCodigoTipoItem = 2131099983;
			
			// aapt resource value: 0x7f06014d
			public const int txtFiltroDescricaoItem = 2131099981;
			
			// aapt resource value: 0x7f06000c
			public const int txtItemCodigoItem = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int txtItemCodigoUnidadeMedida = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int txtItemDescricaoItem = 2131099661;
			
			// aapt resource value: 0x7f06015b
			public const int txtMnuText = 2131099995;
			
			// aapt resource value: 0x7f060067
			public const int txtconsultaDimensionaisEmbalagemQuantidadeItens = 2131099751;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConsultaEstoqueSaldoLocal = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuCustomLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PopUp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PopUpDetalhe = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050011
			public const int ActionButton = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int LorenTheme = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int LorenTheme_AlertDialog = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int LorenTheme_AutoCompleteTextView = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int LorenTheme_Button = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int LorenTheme_ButtonBar = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int LorenTheme_ButtonBarButton = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int LorenTheme_CheckBox = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int LorenTheme_EditText = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int LorenTheme_ExpandableListView = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int LorenTheme_ItemTextAppearance = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int LorenTheme_ListView = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int LorenTheme_ProgressBar = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int LorenTheme_RadioButton = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int LorenTheme_Spinner = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int LorenTheme_SpinnerItem = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int LorenTheme_TabWidget = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int LorenTheme_TextView = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
